name:
  saferoute

services:
  backend:
    container_name: saferoute-backend
    build: ../backend
    ports:
      - 8920:8080
    pull_policy: always

    restart: unless-stopped

  frontend:
    container_name: saferoute-frontend
    build: ../saferoute
    environment:
      - REACT_APP_HOSTPATH=https://saferoute.murraygrov.es
    ports:
      - 8921:3000
    pull_policy: always
    restart: unless-stopped
