services:
  backend:
    container_name: saferoute-backend
    image: ghcr.io/murraygroves/saferoute/backend:dev
    ports:
      - 8920:8080
    pull_policy: always

  frontend:
    container_name: cityfarm-frontend
    image: ghcr.io/murraygroves/saferoute/frontend:dev
    environment:
      - REACT_APP_HOSTPATH=https://saferoute.murraygrov.es
    ports:
      - 8921:3000
    pull_policy: always